name: habit
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^14.2.8
  flutter_animate: ^4.5.0
  shared_preferences: ^2.3.2
  flutter_riverpod: ^2.5.1
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  flutter_onboarding_slider: ^1.0.11


dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^2.5.2
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/onboarding/
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/svg/

  fonts:
    - family:  MyFlutterApp
      fonts:
        - asset: assets/fonts/book_icon.ttf
    - family: "iransans_fa"
      fonts:
        - asset: assets/fonts/iransans_fa_black.ttf
          weight: 700
        - asset: assets/fonts/iransans_fa_bold.ttf
          weight: 600
        - asset: assets/fonts/iransans_fa_medium.ttf
          weight: 500
        - asset: assets/fonts/iransans_fa_regular.ttf
          weight: 400
        - asset: assets/fonts/iransans_fa_light.ttf
          weight: 300
        - asset: assets/fonts/iransans_fa_ultralight.ttf
          weight: 200
    - family: "iransans_en"
      fonts:
        - asset: assets/fonts/iransans_en_black.ttf
          weight: 900
        - asset: assets/fonts/iransans_en_bold.ttf
          weight: 700
        - asset: assets/fonts/iransans_en_medium.ttf
          weight: 500
        - asset: assets/fonts/iransans_en_regular.ttf
          weight: 400
        - asset: assets/fonts/iransans_en_light.ttf
          weight: 300
        - asset: assets/fonts/iransans_en_ultralight.ttf
          weight: 200
flutter_intl:
  enabled: true
